# Generated by Django 4.0.1 on 2022-02-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_alter_city_name'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Traun',
            new_name='Train',
        ),
    ]
